# -*- coding: utf-8 -*-

require 'logger'
require 'cgi/util'
require 'digest/md5'
require 'digest/sha2'
require 'open3'
require 'set'
require 'yaml'
require 'nokogiri'
require 'mimemagic'
require 'haml'

require 'wiki/extensions'
require 'wiki/util'
require 'wiki/i18n'
require 'wiki/hooks'
require 'wiki/timer'
require 'wiki/config'
require 'wiki/routing'
require 'wiki/user'
require 'wiki/helper'
require 'wiki/templates'
require 'wiki/resource'
require 'wiki/plugin'
require 'wiki/application'
